# Generated by Django 3.1.2 on 2020-11-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='session_key',
            field=models.SlugField(null=True),
        ),
    ]
