# Generated by Django 3.1.4 on 2020-12-20 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hub20.apps.blockchain.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_chain_online'),
        ('raiden', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201216_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidenTransferExecution',
            fields=[
                ('transferexecution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transferexecution')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raiden.payment')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.transferexecution',),
        ),
        migrations.CreateModel(
            name='TransferReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('network', models.CharField(choices=[('blockchain', 'blockchain'), ('raiden', 'raiden'), ('internal', 'internal')], max_length=64)),
                ('identifier', models.CharField(max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='internaltransfer',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='internaltransfer',
            name='transfer_ptr',
        ),
        migrations.RemoveField(
            model_name='transferconfirmation',
            name='transfer',
        ),
        migrations.AddField(
            model_name='transfer',
            name='address',
            field=hub20.apps.blockchain.fields.EthereumAddressField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='execute_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExternalTransfer',
        ),
        migrations.DeleteModel(
            name='InternalTransfer',
        ),
        migrations.DeleteModel(
            name='TransferConfirmation',
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='core.transfer'),
        ),
    ]
