# Generated by Django 3.1.1 on 2020-09-26 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hub20.apps.core.models.accounting
import hub20.apps.ethereum_money.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_money', '0002_ethereumtoken_is_listed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_paymentconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField()),
                ('owner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='ethereum_money.ethereumtoken')),
            ],
            options={
                'unique_together': {('token', 'owner_type', 'owner_id')},
            },
        ),
        migrations.CreateModel(
            name='BookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', hub20.apps.ethereum_money.models.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reference_id', models.PositiveIntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ethereum_money.ethereumtoken')),
                ('reference_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbalanceentry',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='userbalanceentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreserve',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='userreserve',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertransferreserve',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='usertransferreserve',
            name='userreserve_ptr',
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('bookentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.bookentry')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.book')),
            ],
            options={
                'abstract': False,
            },
            bases=(hub20.apps.core.models.accounting.TokenTransactionMixin, 'core.bookentry'),
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('bookentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.bookentry')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='core.book')),
            ],
            options={
                'abstract': False,
            },
            bases=(hub20.apps.core.models.accounting.TokenTransactionMixin, 'core.bookentry'),
        ),
        migrations.DeleteModel(
            name='PaymentCredit',
        ),
        migrations.DeleteModel(
            name='UserBalanceEntry',
        ),
        migrations.DeleteModel(
            name='UserReserve',
        ),
        migrations.DeleteModel(
            name='UserTransferReserve',
        ),
    ]
