# Generated by Django 3.1.4 on 2020-12-23 00:05

from django.db import migrations, models
import django.db.models.deletion
import hub20.apps.blockchain.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raiden', '0001_initial'),
        ('core', '0004_auto_20201220_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAddressAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', hub20.apps.blockchain.fields.EthereumAddressField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaidenChannelAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='raiden.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
