# Generated by Django 3.1.4 on 2020-12-27 03:09

from django.db import migrations, models
import django.db.models.deletion
import hub20.apps.blockchain.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0002_chain_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEthereumAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', hub20.apps.blockchain.fields.EthereumAddressField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColdWallet',
            fields=[
                ('baseethereumaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ethereum_money.baseethereumaccount')),
            ],
            bases=('ethereum_money.baseethereumaccount',),
        ),
        migrations.CreateModel(
            name='HierarchicalDeterministicWallet',
            fields=[
                ('baseethereumaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ethereum_money.baseethereumaccount')),
                ('index', models.PositiveIntegerField(unique=True)),
            ],
            bases=('ethereum_money.baseethereumaccount',),
        ),
        migrations.CreateModel(
            name='KeystoreAccount',
            fields=[
                ('baseethereumaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ethereum_money.baseethereumaccount')),
                ('private_key', hub20.apps.blockchain.fields.HexField(max_length=64, unique=True)),
            ],
            bases=('ethereum_money.baseethereumaccount',),
        ),
        migrations.CreateModel(
            name='EthereumToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=500)),
                ('decimals', models.PositiveIntegerField(default=18)),
                ('address', hub20.apps.blockchain.fields.EthereumAddressField(default='0x0000000000000000000000000000000000000000')),
                ('is_listed', models.BooleanField(default=False)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='blockchain.chain')),
            ],
            options={
                'unique_together': {('chain', 'address')},
            },
        ),
    ]
