# Generated by Django 3.1.2 on 2020-10-29 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import hub20.apps.blockchain.fields
import hub20.apps.ethereum_money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blockchain", "0001_initial"),
        migrations.swappable_dependency(settings.ETHEREUM_ACCOUNT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HierarchicalDeterministicWallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "address",
                    hub20.apps.blockchain.fields.EthereumAddressField(db_index=True, unique=True),
                ),
                ("index", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeystoreAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "address",
                    hub20.apps.blockchain.fields.EthereumAddressField(db_index=True, unique=True),
                ),
                ("private_key", hub20.apps.blockchain.fields.HexField(max_length=64, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EthereumToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=500)),
                ("decimals", models.PositiveIntegerField(default=18)),
                (
                    "address",
                    hub20.apps.blockchain.fields.EthereumAddressField(
                        default="0x0000000000000000000000000000000000000000"
                    ),
                ),
                ("is_listed", models.BooleanField(default=False)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="blockchain.chain",
                    ),
                ),
            ],
            options={
                "unique_together": {("chain", "address")},
            },
        ),
        migrations.CreateModel(
            name="AccountBalanceEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    hub20.apps.ethereum_money.models.EthereumTokenAmountField(
                        decimal_places=18, max_digits=32
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_entries",
                        to=settings.ETHEREUM_ACCOUNT_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ethereum_money.ethereumtoken",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="blockchain.transaction"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
