# Generated by Django 3.1.4 on 2020-12-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_money', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalanceEntry',
        ),
    ]
