# Generated by Django 2.2.7 on 2019-12-02 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gnosis.eth.django.models
import hub20.models.ethereum
import hub20.models.payments
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.PositiveIntegerField(choices=[(1, 'Mainnet'), (3, 'Ropsten'), (4, 'Rinkeby'), (5, 'Görli'), (42, 'Kovan')], default=5)),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=60)),
                ('decimals', models.PositiveIntegerField(default=18)),
                ('address', gnosis.eth.django.models.EthereumAddressField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('chain', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', hub20.models.ethereum.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('expiration_time', models.DateTimeField()),
                ('raiden_payment_identifier', models.BigIntegerField(default=hub20.models.payments.generate_raiden_payment_identifier)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub20.EthereumToken')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', hub20.models.ethereum.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub20.EthereumToken')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub20.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', gnosis.eth.django.models.EthereumAddressField(db_index=True, unique=True)),
                ('private_key', gnosis.eth.django.models.HexField(max_length=64, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainTransfer',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub20.Transfer')),
                ('address', gnosis.eth.django.models.EthereumAddressField(db_index=True)),
                ('transaction_hash', gnosis.eth.django.models.HexField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('hub20.transfer',),
        ),
        migrations.CreateModel(
            name='TokenNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', gnosis.eth.django.models.EthereumAddressField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub20.EthereumToken')),
            ],
        ),
        migrations.CreateModel(
            name='Raiden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('address', gnosis.eth.django.models.EthereumAddressField()),
                ('token_networks', models.ManyToManyField(to='hub20.TokenNetwork')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='raiden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hub20.Raiden'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub20.Wallet'),
        ),
        migrations.CreateModel(
            name='BalanceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', hub20.models.ethereum.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub20.EthereumToken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaidenTransfer',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub20.Transfer')),
                ('raiden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub20.Raiden')),
            ],
            options={
                'abstract': False,
            },
            bases=('hub20.transfer',),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('partial', 'partial'), ('completed', 'completed'), ('expired', 'expired'), ('refunded', 'refunded')], default='partial', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='hub20.Payment')),
            ],
            options={
                'get_latest_by': 'created',
                'unique_together': {('payment', 'status')},
            },
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub20.Transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('hub20.transfer',),
        ),
    ]
