# Generated by Django 3.1 on 2020-09-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumtoken',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
