# Generated by Django 3.1 on 2020-09-01 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hub20.apps.ethereum_money.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('ethereum_money', '0001_initial'),
        ('raiden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', hub20.apps.ethereum_money.models.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ethereum_money.ethereumtoken')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='raiden',
            name='url',
            field=models.URLField(default='http://raiden:5001', help_text='Root URL of server (without api/v1)'),
        ),
        migrations.CreateModel(
            name='ServiceDepositTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='raiden.servicedeposit')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='servicedeposit',
            name='raiden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiden.raiden'),
        ),
    ]
