# Generated by Django 3.0.8 on 2020-08-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_money', '0001_initial'),
        ('raiden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiden',
            name='address',
        ),
        migrations.RemoveField(
            model_name='raiden',
            name='id',
        ),
        migrations.AddField(
            model_name='raiden',
            name='keystoreaccount_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ethereum_money.KeystoreAccount'),
            preserve_default=False,
        ),
    ]
