# Generated by Django 3.1 on 2020-09-04 16:12

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raiden', '0002_auto_20200902_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='opened', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='raiden',
            name='url',
            field=models.URLField(help_text='Root URL of server (without api/v1)'),
        ),
        migrations.AlterField(
            model_name='tokennetworkchannelstatus',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='opened', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
