# Generated by Django 3.1 on 2020-09-07 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hub20.apps.ethereum_money.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ethereum_money', '0001_initial'),
        ('blockchain', '0001_initial'),
        ('raiden', '0004_auto_20200904_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidenManagementOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('raiden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiden.raiden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaidenManagementOrderResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('success', models.BooleanField(default=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='raiden.raidenmanagementorder')),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelDepositOrder',
            fields=[
                ('raidenmanagementorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raiden.raidenmanagementorder')),
                ('amount', hub20.apps.ethereum_money.models.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raiden.channel')),
            ],
            options={
                'abstract': False,
            },
            bases=('raiden.raidenmanagementorder',),
        ),
        migrations.CreateModel(
            name='ChannelWithdrawOrder',
            fields=[
                ('raidenmanagementorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raiden.raidenmanagementorder')),
                ('amount', hub20.apps.ethereum_money.models.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raiden.channel')),
            ],
            options={
                'abstract': False,
            },
            bases=('raiden.raidenmanagementorder',),
        ),
        migrations.CreateModel(
            name='JoinTokenNetworkOrder',
            fields=[
                ('raidenmanagementorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raiden.raidenmanagementorder')),
                ('amount', hub20.apps.ethereum_money.models.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('token_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raiden.tokennetwork')),
            ],
            options={
                'abstract': False,
            },
            bases=('raiden.raidenmanagementorder',),
        ),
        migrations.CreateModel(
            name='LeaveTokenNetworkOrder',
            fields=[
                ('raidenmanagementorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raiden.raidenmanagementorder')),
                ('token_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raiden.tokennetwork')),
            ],
            options={
                'abstract': False,
            },
            bases=('raiden.raidenmanagementorder',),
        ),
        migrations.CreateModel(
            name='UserDepositContractOrder',
            fields=[
                ('raidenmanagementorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raiden.raidenmanagementorder')),
                ('amount', hub20.apps.ethereum_money.models.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ethereum_money.ethereumtoken')),
            ],
            options={
                'abstract': False,
            },
            bases=('raiden.raidenmanagementorder', models.Model),
        ),
        migrations.DeleteModel(
            name='ServiceDeposit',
        ),
    ]
