# Generated by Django 3.1 on 2020-09-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiden', '0005_auto_20200907_1600'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('channel', 'identifier', 'sender_address', 'receiver_address')},
        ),
    ]
