# Generated by Django 3.1 on 2020-09-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ethereum_money', '0001_initial'),
        ('raiden', '0003_auto_20200904_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raiden',
        ),
        migrations.CreateModel(
            name='Raiden',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ethereum_money.keystoreaccount',),
        ),
    ]
