# Generated by Django 3.1.1 on 2020-09-30 11:15

from django.db import migrations
import hub20.apps.blockchain.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raiden', '0006_auto_20200913_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='identifier',
            field=hub20.apps.blockchain.fields.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='tokennetworkchannel',
            name='identifier',
            field=hub20.apps.blockchain.fields.Uint256Field(),
        ),
    ]
