# Generated by Django 3.1 on 2020-09-11 00:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransferTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.transaction')),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onchain', to='core.transfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='raidentransaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='raidentransaction',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='raidentransaction',
            name='transfer',
        ),
        migrations.DeleteModel(
            name='BlockchainTransaction',
        ),
        migrations.DeleteModel(
            name='RaidenTransaction',
        ),
    ]
