# Generated by Django 2.2.7 on 2019-11-29 17:38

import blockchain.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import gnosis.eth.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "hash",
                    gnosis.eth.django.models.HexField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                (
                    "chain",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Mainnet"),
                            (2, "Test Network"),
                            (3, "Ropsten"),
                            (4, "Rinkeby"),
                            (5, "Görli"),
                            (42, "Kovan"),
                        ],
                        default=1,
                    ),
                ),
                ("number", models.PositiveIntegerField(db_index=True)),
                ("timestamp", models.DateTimeField()),
                ("parent_hash", gnosis.eth.django.models.HexField(max_length=64)),
                (
                    "uncle_hashes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=gnosis.eth.django.models.HexField(max_length=64), size=None
                    ),
                ),
            ],
            options={"unique_together": {("chain", "hash", "number")}},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hash", gnosis.eth.django.models.HexField(db_index=True, max_length=64)),
                ("from_address", gnosis.eth.django.models.EthereumAddressField(db_index=True)),
                (
                    "to_address",
                    gnosis.eth.django.models.EthereumAddressField(db_index=True, null=True),
                ),
                (
                    "gas",
                    blockchain.fields.Unsigned256IntegerField(decimal_places=0, max_digits=78),
                ),
                (
                    "gas_price",
                    blockchain.fields.Unsigned256IntegerField(decimal_places=0, max_digits=78),
                ),
                (
                    "nonce",
                    blockchain.fields.Unsigned256IntegerField(decimal_places=0, max_digits=78),
                ),
                (
                    "index",
                    blockchain.fields.Unsigned256IntegerField(decimal_places=0, max_digits=78),
                ),
                (
                    "value",
                    blockchain.fields.Unsigned256IntegerField(decimal_places=0, max_digits=78),
                ),
                ("data", models.TextField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blockchain.Block"
                    ),
                ),
            ],
        ),
    ]
