services:
  ethereum:
    image: ethereum/client-go:stable
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 1m
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
    entrypoint:
      - "geth"
      - "--goerli"
      - "--nousb"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3"
      - "--http.vhosts=*"
      - "--http.corsdomain=*"
      - "--ws"
      - "--ws.origins=*"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3"
      - "--datadir=/chaindata"
      - "--cache=4096"
    healthcheck:
      test: ["CMD", "geth", "attach", "http://localhost:8545", "--exec", "eth.blockNumber"]
      interval: 10s
      retries: 10
    networks:
      dev:
        ipv4_address: 10.0.20.90
    volumes:
      - "${HUB20_GETH_MOUNT_PATH:-./docker/volumes/geth/goerli}:/chaindata"
