services:
  raiden:
    image: "mushroomlabs/raiden:${RAIDEN_VERSION:-3.0.0}"
    restart: unless-stopped
    environment:
      RAIDEN_ACCEPT_DISCLAIMER: "true"
      RAIDEN_API_ADDRESS: 0.0.0.0:5001
      RAIDEN_ENABLE_MONITORING: "true"
      RAIDEN_ENVIRONMENT_TYPE: development
      RAIDEN_KEYSTORE_PATH: /keystore
      RAIDEN_MATRIX_SERVER: "${HUB20_RAIDEN_TRANSPORT_SERVICE_URL:-https://transport.transport01.raiden.network}"
      RAIDEN_NETWORK_ID: goerli
      RAIDEN_PATHFINDING_SERVICE_ADDRESS: "${HUB20_RAIDEN_PATH_FINDING_SERVICE_URL:-https://pfs.transport01.raiden.network}"
      RAIDEN_ROUTING_MODE: pfs

    volumes:
      - raiden-data:/root/.raiden

volumes:
  raiden-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${RAIDEN_DATA_STORAGE_PATH:-/srv/raiden}
