x-logging: &loki-logging
  depends_on:
    - loki
  logging:
    driver: loki
    options:
      loki-url: "http://loki:3100/api/prom/push"

services:
  flower:
    image: mher/flower

  loki:
    image: grafana/loki:2.4.0
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.4.0
    command: -config.file=/etc/promtail/config.yml

  influxdb:
    image: influxdb:1.7
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest

  # web:
  #   <<: *loki-logging

  # celery:
  #   <<: *loki-logging

  # rabbitmq:
  #   <<: *loki-logging

  # redis:
  #   <<: *loki-logging

  # db:
  #   <<: *loki-logging
