version: '3'

x-logging: &loki-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/api/prom/push"

services:
  flower:
    image: mher/flower
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: "${HUB20_BROKER_URL:-redis://redis:6379/0}"
      FLOWER_PORT: 8888

    logging: *loki-logging
    ports:
      - 8888:8888
    networks:
      dev:
        ipv4_address: 10.0.20.81

  loki:
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      dev:
        ipv4_address: 10.0.20.82

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      dev:

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      dev:
        ipv4_address: 10.0.20.83


  web:
    logging: *loki-logging

  celery:
    logging: *loki-logging

  db:
    logging: *loki-logging

  event_publisher:
    logging: *loki-logging
